name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print-greetings
        run: echo "hello wordl!"
      - name: Print Goodbye
        run: echo "Done bye!"
